### ISSUE TITLE
4月19日使用发现一个问题，求助

### ISSUE THREAD

**Issue by zoujiegogogo** [fwnan/envshell#1]
大神你好，首先我尝试使用克隆的项目的方式来运行脚本，跑到ECS服务器上运行，发现有报错。然后我删除提示的空行，但有一个问题我解决不掉。
![image](https://user-images.githubusercontent.com/48706279/233083301-5d3643dc-b86c-46f8-afe8-895bb37e26b0.png)
可是shell脚本没有50行代码，如果我不清楚这个问题是啥问题导致的。然后我尝试使用curl请求发现网址已经挂掉了。希望大佬看到之后能提供下支持，谢谢
![image](https://user-images.githubusercontent.com/48706279/233082830-73890279-c30f-4f3d-96b4-77460c388df0.png)

**Comment by zoujiegogogo** [comment]
忘记提供我运行的脚本信息了，我运行的是maven.sh,我给了它一个运行权限。

**Comment by zoujiegogogo** [comment]
噢噢，后面先按i进去插入模式，复制粘贴进去。可以正常运行，不会报其他错误。如果要用需要修改下下载地址，之前3.8.6版本已经不在了。

**Comment by fwnan** [comment]
抱歉, 没太关注github的issues信息, 你所提出的问题已经修复完成.
maven的镜像地址已改成官方提供;
至于readme不可用问题, 是因为之前改动仓库名字忘记同步修改, 已调整完毕;
